### PR TITLE
Remove boolean options fallback

### PR DESCRIPTION
**Pull request by tytan652**
While unnecessary since all of them have a default value
Having build-bundle set to false was is fact turning it to true through the fallback

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
oh, good catch

**Comment by bilelmoussaoui** [comment]
i wonder why the ncc build diff is so huge this time

**Comment by tytan652** [comment]
> i wonder why the ncc build diff is so huge this time

I don't know, I just install ncc and done the command. Should I done another npm/yarn command before ?

**Comment by tytan652** [comment]
I think I found the issue, I think need to use `yarn install --pure-lockfile`

**Comment by tytan652** [comment]
Dist files should be fixed and good now.

**Pull request merged**
